### ISSUE TITLE
Error: Alloy is not defined

### ISSUE THREAD

**Issue by jonasfunk** [caffeinalab/ti.goosh#10]
I am facing the same issue as [described here on JIRA](https://jira.appcelerator.org/browse/ALOY-1504): 
1. App is closed manually in background 
2. There is a notification in notification bar for the app
3. App is opened by tapping on the notification.
4. An error with "Alloy is not defined" is displayed.

Have you experienced the same issue, but somehow managed to find a solution?

**Comment by kopiro** [comment]
Hi, could you try this latest fix-build (1.1.1):
[ti.goosh-android-1.1.1.zip](https://github.com/caffeinalab/ti.goosh/files/399486/ti.goosh-android-1.1.1.zip)

**Comment by jonasfunk** [comment]
Thanks for reaching out @kopiro! I've just tried 1.1.1 but it doesn't seem to fix it. Still getting the same error. Are you not experiencing this issue?

**Comment by mbilwar** [comment]
I am facing the same issue from last 2 days on local push notification. Did anyone found the solution for this issue?

Activity: App is closed. When Clicked on Local Notification it will open the app but unfortunately it will crash the app by showing above error message and when i click on kill it will load app again without any error message.

**Comment by kopiro** [comment]
Could you try to wrap your callback in a setTimeout?

```
TiGoosh.registerForPushNotifications({
   callback: function() {
      setTimeout(function() {
         // Alloy...
      }, 0);
   }
});
```

**Comment by progress44** [comment]
Could you try this build?

[ti.goosh-android-1.1.3.zip](https://github.com/caffeinalab/ti.goosh/files/401197/ti.goosh-android-1.1.3.zip)

**Comment by jonasfunk** [comment]
Thank you @kopiro and @progress44. Have tested your suggestions with the timeout and 1.1.3 build.  None of the solutions seems to work. But I think that it is some kind of a random timing issue, as approx. 1 out of 10 times the app does not show the error, and starts up as it should.

**Comment by progress44** [comment]
@jonasfunk does it give you the same error with the new build?

**Comment by jonasfunk** [comment]
Yes it does. Still Alloy that is undefined.

**Comment by jknightsbm** [comment]
We are having this problem as well.  Same symptoms.
Using v1.5.0, commit 2411339.

**Comment by boudellaredouane** [comment]
On a side note, i do have a probleme with Alloy note being defined when coming from a push notification, this problem happens on any lib commonjs that i'm using.

The work around was to force require alloy on every lib js :
var Alloy = require("alloy");
// from now on, Alloy is defined correctly.

**Comment by kopiro** [comment]
Ok, so could be an Alloy/Ti problem?
