### ISSUE TITLE
How can we use both ios?

### ISSUE THREAD

**Issue by kerbooo** [caffeinalab/ti.goosh#103]
Is there any example this great module with iOS both?

**Comment by kopiro** [comment]
@kerbooo Hi, this module is only for Android.

**Comment by kerbooo** [comment]
Yes I know. But may be there is a approach for using both android and ios.

**Comment by progress44** [comment]
@kerbooo what the module offers, can be achieved natively on iOS. Check out [Trimethyl](https://github.com/trimethyl) and in particular [Trimethyl notifications](https://github.com/trimethyl/trimethyl/wiki/Notifications) for a seamless implementation
