### ISSUE TITLE
Failed to get GCM Registration Token:TIMEOUT

### ISSUE THREAD

**Issue by Wingee** [caffeinalab/ti.goosh#104]
I'm currently getting this error message:

E/ti.goosh.RegistrationIntentService: Failed to get GCM Registration Token:TIMEOUT

I'm guessing this must be an error at the Google side? The device has internet connectivity

**Comment by progress44** [comment]
Well, Google hardly has problems of the sort, it may be because of a limit on your network or a firewall. Try using a different network.
