### ISSUE TITLE
Firebase support -  internal dependencies

### ISSUE THREAD

**Issue by antonioduran** [caffeinalab/ti.goosh#121]
Hello. As you know google will be deprecated GCM in April 11th, so this module is working pretty good with GCM, and the latest version of titanium 7.5.0.GA, but does anybody know whether this module will have support for firebase? I mean to update all the internal dependencies of the module to firebase

Thanks.

**Comment by Jei** [comment]
Hi,
we are in the process of deprecating this module and transitioning to [Titanium Firebase](https://github.com/hansemannn/titanium-firebase). I will update the README with a deprecation notice and a guide on how to move Ti.Goosh projects to TiFirebase.

**Comment by caioiglesias** [comment]
Would this module stop registering for push after April 11th?

**Comment by Jei** [comment]
@caioiglesias yes, that's correct. As stated by Google:
>As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features.

**Comment by caioiglesias** [comment]
I researched a bit more and found this info:

> **What happens to my users who don't update their apps?**
> As long as users have GCM logic in their apps, they will still receive messages. FCM is backwards compatible with GCM, so even if you don't update your server endpoint now, you can still update your app's logic, and vice versa.

https://android-developers.googleblog.com/2018/04/time-to-upgrade-from-gcm-to-fcm.html

**Comment by caioiglesias** [comment]
Also this:

> **How long do I have to migrate to FCM?**
> We will turn off most GCM services in April 2019, so you should plan to have most of your services migrated by then.
> 
> Note that client SDKs and GCM tokens will continue to work indefinitely. However, you won't be able to target the latest version of Google Play Services in your Android app unless you migrate to FCM.

https://developers.google.com/cloud-messaging/faq

**Comment by Jei** [comment]
I didn't know that the GCM library would work even after the transition to Firebase. Thank you for the info. I thought that only the server APIs where compatible.

**Comment by ClaudiuStefaniga** [comment]
hello, will be this module maintained for Titanium SDK 8.X, also, is it compatible with FCM? thanks!

**Comment by Jei** [comment]
Hi,
as stated [here](https://github.com/caffeinalab/ti.goosh/issues/121#issuecomment-465489806), this module is not maintained anymore. We cannot guarantee that it will work properly with Firebase notifications.
