### ISSUE TITLE
Multiple notifications in the notification drawer not opening app

### ISSUE THREAD

**Issue by jonasfunk** [caffeinalab/ti.goosh#13]
I have some issues with the usage pattern described below:

1) App receives >1 notifications, which is placed in the notification drawer. 
2) From the drawer the most recent notification is tapped, and opens the app.
3) If the app is backgrounded and the other remaining notifications is tapped, the app is _not_ opened, but the tapped notification is removed from the drawer.
4) If a new notification is received, the new notification opens the app.

Have tested on several devices, with the same result. 

Is this normal behaviour or am I missing something?

**Comment by netoramalho** [comment]
I could reproduce the same problem you besides other problems with multiple notifications, I'll do some tests.

**Comment by DFoxinator** [comment]
Do you know if this issue has been fixed?

**Comment by progress44** [comment]
@dfoxinator we are working in it. There still remains an issue since we want to maintain compatibility with how iOS handles notifications
