### ISSUE TITLE
Conflict with ti.map module

### ISSUE THREAD

**Issue by CREATIVE-KAIZEN** [caffeinalab/ti.goosh#14]
Hello, 
First of all I would like to thank you for great job you do!
Unfortunately I cannot compile app if I use ti.map (2.3.10) and ti.goosh (1.3.0) modules at the same time. If I compile application without ti.map OR ti.goosh no error occurs. 
Please provide update or some information how I can fix this problem (I need to use both maps and notifications) in my app.

Here is the error:

Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/dynamic/zzd$zza$zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/dynamic/zzg$zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/dynamic/zzd;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/dynamic/zzd$zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/dynamic/zzg;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/dynamic/zze;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/playlog/internal/zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/playlog/internal/zzb;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/playlog/internal/zzd;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR] :  	... 4 more

Regards

**Comment by kopiro** [comment]
Hi @CREATIVE-KAIZEN, I'm sorry but this is not a module bug, but a TItanium + Android bug (or behaviour) regarding the multidex.

You can read my article here to handle it: https://medium.com/all-titanium/deal-with-titanium-modules-and-its-missing-support-for-android-multidex-546de5486d13

**Comment by CREATIVE-KAIZEN** [comment]
Hi @kopiro. Thank you for a fast answer. Sorry to hear it is Titanium + Android bug.
Could you consider adding additional .jar for ti.map users to your repository? That module is 'basic' and official Titanium module and solution described in your article is really convoluted. I don't know how the proper proguard.conf for your module should look like (what classes etc). Could you provide how that file should look like to work with your module and not cause conflict with ti.map?
Regards
