### ISSUE TITLE
ti.goosh Google Play Service library creation

### ISSUE THREAD

**Issue by CREATIVE-KAIZEN** [caffeinalab/ti.goosh#15]
Hello,
Due to Titanium + Android bug (or behaviour) regarding the multidex, if user would have an app using ti.goosh module with ti.map module then will have problems during compilation.
Solution suggested by @kopiro is to create stripped version of Google Play Services (https://medium.com/all-titanium/deal-with-titanium-modules-and-its-missing-support-for-android-multidex-546de5486d13).
Could you provide how is your proguard.conf file looking like (what are required classes), so any user could modify it to achieve simultaneously work of both modules?
Thanks in advance.

**Comment by progress44** [comment]
Hi! Here you have an example of the [proguard.conf](https://gist.github.com/progress44/505ebba80f12625a949fa3bfef028adc) file while using the module with ti.ga  

It should work by adding the maps package such as 

```
-keep public class com.google.android.gms.maps.** {
  public protected *;
}
```
then follow the rest of the guide by kopiro

**Comment by CREATIVE-KAIZEN** [comment]
Hello, Thank you for quick answer. Your example is the same as in link I provided. The thing is, that I don't use ti.ga. I am using ti.map, so I planned modyfing ti.goosh google play service library (removing second declaration). That's why I am asking what classes should be provided for ti.goosh? But maybe I am thinking wrong. Nonetheless I will try to do as u suggested today.

**Comment by CREATIVE-KAIZEN** [comment]
Hello,
I tried a dozen of modification of google-play-services for both ti.map and ti.goosh, but I always get error similar to this if I try to compile

[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/zzb;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/zzd;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/UserRecoverableException;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ConnectionResult;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/zzc;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesNotAvailableException;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesRepairableException;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/api/GoogleApiClient$OnConnectionFailedListener;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR] :  	... 4 more

Please help me how I can create proper proguard.conf for ti.map or ti.goosh to make both modules working at the same time. Thanks in advance for any help...

**Comment by kopiro** [comment]
@CREATIVE-KAIZEN 
https://github.com/caffeinalab/ti.goosh/tree/master/gps-jars

**Comment by CREATIVE-KAIZEN** [comment]
@kopiro,
Thanks, for so quick update. You are awesome! But I still have a problem.

I overwrited:
/ti.goosh/lib/google-play-services-tigoosh.jar
and
/ti.map/lib/google-play-services-base.jar

Application is compiling without problem, but when i open window with map I get such error (causing app crash):

[INFO] :   dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method ti.modules.titanium.geolocation.GeolocationModule.hasLocationPermissions
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 30: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I
[INFO] :   dalvikvm: Could not find method android.app.Activity.requestPermissions, referenced from method ti.modules.titanium.geolocation.GeolocationModule.requestLocationPermissions
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 80: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
[INFO] :   dalvikvm: Could not find method com.google.android.gms.dynamic.zzd$zza.zzbg, referenced from method com.google.android.gms.maps.model.MarkerOptions.<init>
[WARN] :   dalvikvm: VFY: unable to resolve static method 19008: Lcom/google/android/gms/dynamic/zzd$zza;.zzbg (Landroid/os/IBinder;)Lcom/google/android/gms/dynamic/zzd;
[INFO] :   dalvikvm: Could not find method com.google.android.gms.common.internal.safeparcel.zzb.zzac, referenced from method com.google.android.gms.maps.model.zzf.zza
[WARN] :   dalvikvm: VFY: unable to resolve static method 18122: Lcom/google/android/gms/common/internal/safeparcel/zzb;.zzac (Landroid/os/Parcel;)I
[INFO] :   dalvikvm: Could not find method com.google.android.gms.common.internal.safeparcel.zza.zzab, referenced from method com.google.android.gms.maps.model.zzf.zzeQ
[WARN] :   dalvikvm: VFY: unable to resolve static method 18058: Lcom/google/android/gms/common/internal/safeparcel/zza;.zzab (Landroid/os/Parcel;)I
[WARN] :   TiUIScrollView: (main) [49595,50241] Scroll direction could not be determined based on the provided view properties. Default VERTICAL scroll direction being used. Use the 'scrollType' property to explicitly set the scrolling direction.
[INFO] :   dalvikvm: Could not find method com.google.android.gms.common.internal.safeparcel.zzb.zzac, referenced from method com.google.android.gms.maps.zza.zza
[WARN] :   dalvikvm: VFY: unable to resolve static method 18122: Lcom/google/android/gms/common/internal/safeparcel/zzb;.zzac (Landroid/os/Parcel;)I
[INFO] :   dalvikvm: Could not find method com.google.android.gms.common.internal.safeparcel.zza.zzab, referenced from method com.google.android.gms.maps.zza.zzeI
[WARN] :   dalvikvm: VFY: unable to resolve static method 18058: Lcom/google/android/gms/common/internal/safeparcel/zza;.zzab (Landroid/os/Parcel;)I
[WARN] :   dalvikvm: Unable to resolve superclass of Lcom/google/android/gms/maps/SupportMapFragment$zzb; (2427)
[WARN] :   dalvikvm: Link of class 'Lcom/google/android/gms/maps/SupportMapFragment$zzb;' failed
[ERROR] :  dalvikvm: Could not find class 'com.google.android.gms.maps.SupportMapFragment$zzb', referenced from method com.google.android.gms.maps.SupportMapFragment.<init>
[WARN] :   dalvikvm: VFY: unable to resolve new-instance 2659 (Lcom/google/android/gms/maps/SupportMapFragment$zzb;) in Lcom/google/android/gms/maps/SupportMapFragment;
[WARN] :   dalvikvm: DexOpt: method is in an interface
[INFO] :   dalvikvm: Could not find method com.google.android.gms.common.internal.zzu.zzbY, referenced from method com.google.android.gms.maps.SupportMapFragment.getMapAsync
[WARN] :   dalvikvm: VFY: unable to resolve static method 18609: Lcom/google/android/gms/common/internal/zzu;.zzbY (Ljava/lang/String;)V
[WARN] :   dalvikvm: VFY:  rejecting opcode 0x71 at 0x0002
[WARN] :   dalvikvm: VFY:  rejected Lcom/google/android/gms/maps/SupportMapFragment;.getMapAsync (Lcom/google/android/gms/maps/OnMapReadyCallback;)V
[WARN] :   dalvikvm: Verifier rejected class Lcom/google/android/gms/maps/SupportMapFragment;
[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa4b98648)
[ERROR] :  TiApplication: (main) [28,50269] Sending event: exception on thread: main msg:java.lang.VerifyError: com/google/android/gms/maps/SupportMapFragment; Titanium 5.4.0,2016/08/10 05:44,4ba4c0a
[ERROR] :  TiApplication: java.lang.VerifyError: com/google/android/gms/maps/SupportMapFragment
[ERROR] :  TiApplication: 	at ti.map.TiUIMapView.createFragment(TiUIMapView.java:110)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.view.TiUIFragment.<init>(TiUIFragment.java:50)
[ERROR] :  TiApplication: 	at ti.map.TiUIMapView.<init>(TiUIMapView.java:69)
[ERROR] :  TiApplication: 	at ti.map.ViewProxy.createView(ViewProxy.java:80)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:493)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:479)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:517)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:501)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:479)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:517)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:501)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:479)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:517)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:501)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:479)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:680)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:574)
[ERROR] :  TiApplication: 	at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:263)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:33)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:559)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:673)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] :  TiApplication: 	at android.app.Activity.performCreate(Activity.java:5133)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:99)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:137)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5103)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:525)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
[ERROR] :  TiApplication: 	at dalvik.system.NativeStart.main(Native Method)

**Comment by kopiro** [comment]
What version of ti.map are you using?

**Comment by CREATIVE-KAIZEN** [comment]
2.3.10, but I created inside project version 2.3.11 which is same, only with changed .jar files - to be sure I am not changing global ti.map module and be sure if running the version with updated .jar.
But I think it shouldn't have any influence.

**Comment by kopiro** [comment]
@CREATIVE-KAIZEN Wait, you have to override your local copy of modules (inside your app).

**Comment by CREATIVE-KAIZEN** [comment]
Yes. I work on module copies inside the project. I just say that i also changed its number to be sure I compile the versions from project and not global one.

**Comment by kopiro** [comment]
Ok, I'll make a test.
Anyway, you can be sure that your local module has priority over globals ;)

**Comment by kopiro** [comment]
Could you try to download this one? 
https://github.com/caffeinalab/ti.goosh/blob/master/gps-jars/google-play-services-gcm%2Bmaps.jar

**Comment by CREATIVE-KAIZEN** [comment]
Hello,
Thank you, but now it is not compiling:

[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$13;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/SupportMapFragment;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$1;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/zza;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/SupportStreetViewPanoramaFragment$zzb;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$OnCameraChangeListener;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/zzb;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/GoogleMap$OnMapLongClickListener;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/maps/StreetViewPanorama$3;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR] :  	... 4 more

ti.map has two jar files: 
google-play-services-base.jar
google-play-services-map.jar

Maybe both of them should be modified?

**Comment by kopiro** [comment]
@CREATIVE-KAIZEN You have to delete!

**Comment by CREATIVE-KAIZEN** [comment]
@kopiro:
But delete what?
I overwrite (delete and copy new file with same name) google-play-services-tigoosh.jar (ti.goosh) and google-play-services-base.jar (ti.map). I leave gson.jar (ti.gosh) and google-play-services-map.jar (ti.map) untouched as it was written here: https://github.com/caffeinalab/ti.goosh/tree/master/gps-jars

**Comment by progress44** [comment]
@CREATIVE-KAIZEN the map libraries are already included in the google-play-services-tigoosh.jar You don't need it in ti.map. Delete google-play-services-map.jar

**Comment by kopiro** [comment]
@CREATIVE-KAIZEN basically, delete all GPS jars and replace with the one downloaded.

**Comment by CREATIVE-KAIZEN** [comment]
@kopiro, @progress44:
I did as you said. I had to change google-services-version number also.
Thank you guys for all the help. I really appreciate that!
