### ISSUE TITLE
Cancel a notification

### ISSUE THREAD

**Issue by netoramalho** [caffeinalab/ti.goosh#16]
How can I cancel a notification?
I need because the user can not click on the notification and open the application to see the contents.

**Comment by netoramalho** [comment]
I could cancel all notifications using
Titanium.Android.NotificationManager.cancelAll();

But it worked not cancel only one
Titanium.Android.NotificationManager.cancel(id);

**Comment by kopiro** [comment]
Effectively it should work in your way (using negative number).

Could you provide the complete code + payload of the notif?
