### ISSUE TITLE
Titanium Javascript Runtime Error

### ISSUE THREAD

**Issue by kezai** [caffeinalab/ti.goosh#2]
Hello,

I got this error : 

[ERROR] :  TiExceptionHandler: (main) [718,718] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,718] - In app.js:14,9
[ERROR] :  TiExceptionHandler: (main) [0,718] - Message: Uncaught Error: Failed resolution of: Lcom/google/android/gms/R$string;
[ERROR] :  TiExceptionHandler: (main) [0,718] - Source: TiGoosh.registerForPushNotifications({
[ERROR] :  V8Exception: Exception occurred at app.js:14: Uncaught Error: Failed resolution of: Lcom/google/android/gms/R$string;

Titanium 5.3.0 GA
 
I installed module from help/install mobile module with ti.goosh-android-1.0.1.zip file.

I used the code sample in example folder in module, What I did wrong please ?

Thanks in advance.

**Comment by DFoxinator** [comment]
Were you ever able to solve this? I'd like to use this module too.

**Comment by kopiro** [comment]
Hi, I'll try to understand the problem today! :)

**Comment by kopiro** [comment]
Hello, We have investigated about this issue and it's related to a missing Google Play Service integration.

**Comment by sabotah** [comment]
I'm having the same issue after following the guide that you wrote regarding google-play-services.jar conflicts: https://medium.com/all-titanium/deal-with-titanium-modules-and-its-missing-support-for-android-multidex-546de5486d13#.n9n2f6n95

Although my error clearly states: Uncaught Error: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability

**Comment by sabotah** [comment]
Nevermind, I included com.google.android.gms.common.GoogleApiAvailability in the proguard config and it is now working :) thanks

**Comment by necrocyber** [comment]
I so with Android 5.1.1 , 5.3.1 SDK. There is another way to solve than sea deliveries not THAT long explanation ?

**Comment by mark22** [comment]
I get the same exact issue running Goosh.  Was there ever an actual resolution?

Ti.Goosh 2.0.6
Titanium 6.0.2

[ERROR] :  TiExceptionHandler: (main) [204,206] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,206] - In /app.js:341,11
[ERROR] :  TiExceptionHandler: (main) [0,206] - Message: Uncaught Failed resolution of: Lcom/google/android/gms/R$string;
[ERROR] :  TiExceptionHandler: (main) [0,206] - Source: 		TiGoosh.registerForPushNotifications({
[ERROR] :  V8Exception: Exception occurred at /app.js:341: Uncaught Failed resolution of: Lcom/google/android/gms/R$string;
[ERROR] :  V8Exception: Failed resolution of: Lcom/google/android/gms/R$string;
