### ISSUE TITLE
already added error during compile

### ISSUE THREAD

**Issue by Luca4k4** [caffeinalab/ti.goosh#20]
Hi, i'm trying to use Ti.Map and Ti.Goosh together. I followed step by step your procedure (this is a screenshot: http://s11.postimg.org/bhvi7dg8j/tre.png ), but i get this error during compile:

`[ERROR] Failed to run dexer:
[ERROR]   
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/AccountPicker;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ConnectionResult;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ErrorDialogFragment;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GoogleApiAvailability;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesNotAvailableException;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesRepairableException;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesUtil;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesUtil$zza;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/Scopes;
[ERROR]   
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.RuntimeException: Translation has been interrupted
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR]         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR]         at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR]         at com.android.dx.command.Main.main(Main.java:106)
[ERROR] Caused by: java.lang.InterruptedException: Too many errors
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR]         ... 4 more
`

my version.xml files are both: 

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <integer name="google_play_services_version">8487000</integer>
</resources>
```

I'm using Genymotion as emulator.

What i wrong? 

Luca

**Comment by progress44** [comment]
Hi Luca,
Check out this related issues [#14](https://github.com/caffeinalab/ti.goosh/issues/14), [#15](https://github.com/caffeinalab/ti.goosh/issues/15) which have already been resolved.

**Comment by Luca4k4** [comment]
Hey, 
sorry if i open again but before to publish my error i've read all other questions about same issue. I followed the procedure that worked for #15 but i still have the problem.
I installed your last version of ti.goosh (very thank for this! it will be very usefull for me!) and version 3.0 of ti.map, together installed by " gittio install .... ", then i replaced all GPS file in lib, overwritten the version of version.xml files and added the string "<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>" to tiapp.xml

If it's interesting, i'm using Titanium (sdk v.5.4.0.GA) with TiShadow. I'm using as other module "TiParseJs" and i have the others basic modules (created by TiShadow, but without the 'lib' directory, so i suppose they don't use GPS).

Could you help me? I need a solution for my universitary project..

Regards, Luca

**Comment by progress44** [comment]
Hi @Luca4k4,
delete all the google play services libraries (from ti.map module and Ti.Goosh). Get the GPS jar that suits you the best from this repository, you can find it under gps/jars. It seems like you'd need [GCM + Maps](https://github.com/caffeinalab/ti.goosh/blob/master/gps-jars/google-play-services-gcm%2Bmaps.jar)
Copy this jar library inside the ti.goosh module folder under lib.
TiParseJS is a commonJS module so it doesn't cause any problems. Make sure you're using the latest version of Ti.Goosh (1.5.0)

**Comment by Luca4k4** [comment]
Thank you for quickly reply. I replaced your "GCM + Maps" file with "Google-play-services-tigoosh" (under tigoosh/1.5.0/lib) and with "Google-play-services-map" and "Google-play-services-map" (under timap/3.0/lib) but anyway the error occured. There is a specific name that should the new jars file have?

**Comment by progress44** [comment]
no they're included automatically but you have to delete the `google-play-services-map` under `ti.map/3.0/lib`

**Comment by Luca4k4** [comment]
i removed google-play-services-map and google-play-services-base from lib in timap

**Comment by progress44** [comment]
can you paste the error log?

**Comment by Luca4k4** [comment]
i'm trying with version 2.3.10 of ti.map but the error still occure.. This is my console:

[ERROR] Failed to run dexer:
[ERROR]   
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/AccountPicker;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ConnectionResult;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ErrorDialogFragment;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GoogleApiAvailability;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesNotAvailableException;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesRepairableException;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesUtil;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesUtil$zza;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/Scopes;
[ERROR]   
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.RuntimeException: Translation has been interrupted
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
[ERROR]         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
[ERROR]         at com.android.dx.command.dexer.Main.run(Main.java:277)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR]         at com.android.dx.command.Main.main(Main.java:106)
[ERROR] Caused by: java.lang.InterruptedException: Too many errors
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
[ERROR]         ... 4 more

**Comment by progress44** [comment]
Are you sure you're not using any other modules?

**Comment by Luca4k4** [comment]
This is all my modules: http://s13.postimg.org/yv8zkdzgn/Schermata_del_2016_09_24_01_24_13.png

**Comment by progress44** [comment]
Try removing all of them except Ti.map and ti.goosh and see if the problem persists then add them one by one

**Comment by Luca4k4** [comment]
i still have the problem with only the two modules.. i found a previously global installation of ti.map, i'm trying to remove it but i think that local > global, or not?
Anyway, have i to remove the gson.jar file under /ti.goosh/lib too ?

**Comment by Luca4k4** [comment]
Removing global installation of TiMap I SOLVED THE PROBLEM! Now compile!!!

**Comment by Luca4k4** [comment]
Thank you @progress44 for the time you dedicated to my problem!
