### ISSUE TITLE
sendMessage invoked but no messageCallback defined

### ISSUE THREAD

**Issue by necrocyber** [caffeinalab/ti.goosh#21]
Hi.

When sending a notification from the server console appcelerator answer me this: [ERROR]: E / ti.goosh.TiGooshModule: sendMessage Invoked messageCallback but not defined

A This message is?

Thank you

**Comment by progress44** [comment]
Hi @necrocyber 
Can you provide the code to how you are registering for push notifications using the module?

**Comment by necrocyber** [comment]
Hi.
I am using the same example available.

`TiGoosh.registerForPushNotifications({
	// The callback to invoke when a notification arrives.
	callback: function(e) {
var data = JSON.parse(e.data || '');
									console.log(e);
							    },
							
							    // The callback invoked when you have the device token.
							    success: function(e) {
							
							        // Send the e.deviceToken variable to your PUSH server
							        Ti.API.log('Notifications: device token is ' + e.deviceToken);
									token = e.deviceToken;
							    },
							
							    // The callback invoked on some errors.
							    error: function(err) {
							        Ti.API.error('Notifications: Retrieve device token failed', err);
							    }
							});`

**Comment by progress44** [comment]
Do you see `'Notifications: device token is ' + e.deviceToken` in the logs?

**Comment by necrocyber** [comment]
Hi.
I am using the same example available.

**Comment by necrocyber** [comment]
If there has been no problems and showed me the token console

**Comment by progress44** [comment]
@necrocyber was the app closed, in background or open when you sent the push notification?

**Comment by necrocyber** [comment]
When the app is open, console shows me the error mentioned. When the app is running in the background or simply closed, do not run the callBack.

**Comment by necrocyber** [comment]
Now ... I realized that when I register the device in GCM shows me the token console, but also throws the following error

`[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.`

**Comment by kopiro** [comment]
That's normal.

Could you paste your `adb logcat | grep Goosh`

**Comment by necrocyber** [comment]
What is the purpose of delivering that kind of log?

**Comment by kopiro** [comment]
To debug?

**Comment by necrocyber** [comment]
This is correct?

`<application android:theme="@style/materialTheme">
                <activity
                    android:configChanges="keyboardHidden|orientation"
                    android:name="org.appcelerator.titanium.TiActivity" android:screenOrientation="portrait"/>
                <activity android:name="android.hardware.Camera" android:screenOrientation="portrait"/>
                <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version"/>
            </application>`

**Comment by necrocyber** [comment]
I work with version 1.5, api Ti.5.2.2

**Comment by necrocyber** [comment]
I do not understand why, but now is working and not run changes in settings
