### ISSUE TITLE
Blank black screen when going to notif

### ISSUE THREAD

**Issue by DFoxinator** [caffeinalab/ti.goosh#24]
Using the latest version (1.6.2), I've had an issue reported from some users. It doesn't happen a all the time, but it has been happening fairly frequently. Sometimes when the app is opened from a notif, it goes directly to a blank, all-black screen. But if you hit the system back button, it goes to the correct screen showing the correct content. Any idea why that black screen might be coming up?

**Comment by kopiro** [comment]
@DFoxinator The first thing that I can imagine is that the PushHandlerActivity doesnt finish itself when it's called. I'll investigate on it

**Comment by DFoxinator** [comment]
@kopiro awesome, thanks, much appreciated. Let me know if you'd like me to test anything.

**Comment by DFoxinator** [comment]
@kopiro any further ideas on this? I ended up going back to a custom built version of the module because that seemed to work better (mainly because of this issue).

**Comment by DFoxinator** [comment]
@kopiro sorry to bother you again about this but I'm curious if anyone else is seeing this issue or if it has been fixed? We were seeing it a lot and are still stuck on a non-official version of this plugin because of it. I would love to be able to use the latest one.

**Comment by kopiro** [comment]
@DFoxinator not yet. maybe next week.

**Comment by appsol1** [comment]
I just came across this awesome module for push notifications. Works like a charm but unfortunately suffering from this same issue @DFoxinator reported. Any idea when it could be fixed? Its like a show stopper for us :(

**Comment by progress44** [comment]
hopefully this week :)

**Comment by appsol1** [comment]
Great 👍 Our app release can wait for it to be fixed then :D

**Comment by kopiro** [comment]
@DFoxinator or @appsol1 I need a base app that has this issue. 
I can't replicate.

**Comment by DFoxinator** [comment]
@kopiro do you need the source code for an app or would an APK of an app that has the issue work?

My app is kind of a mess/it would be very hard to decipher the code at this point, but I can easily put together an APK with the version that shows the black screen so you can see it happening and try to find consistent reproduction steps. Please let me know if that would help.

**Comment by DFoxinator** [comment]
Or the other option is I can try to see if I can find a simple test case that shows the issue, but I'm not sure how difficult that will be being that you weren't able to reproduce it. Hopefully maybe @appsol1 as a simpler case that demonstrates the issue.

**Comment by kopiro** [comment]
Can you just show me the code are you using to register the push notifications? 
For example, are you registering in the alloy.js file or something other?

**Comment by kopiro** [comment]
@DFoxinator could you just try the latest build? v2.0.2

**Comment by DFoxinator** [comment]
@kopiro awesome, thanks for the new build, I will start testing it right now and report back later.

My app doesn't use Alloy and is pure JavaScript.

For registering, this code runs once when the app starts in my app.js file:

```
var TiGoosh = require('ti.goosh');
TiGoosh.registerForPushNotifications({
	callback: function(e) {
    	receivePush(e);
	},
	success: function(e) { },
	error: function(err) { }
}); 
```

**Comment by DFoxinator** [comment]
@kopiro just to give you an update - I've done some basic testing and so far so good! I plan to do a lot more testing in the beginning of this week so I'll keep you updated. In the past it sometime seemed to take a while to show up, but I'll try to confirm the bug is gone with some more thorough testing. Thanks again.

**Comment by kopiro** [comment]
@DFoxinator any news?

**Comment by DFoxinator** [comment]
@kopiro sorry for my slow response! I think the bug is gone. I got one similar report but it was probably caused by something else and overall it seems great. Thanks a bunch and I would say this is good to go.

**Comment by kopiro** [comment]
Yee! 👍
