### ISSUE TITLE
Failed to run dexer

### ISSUE THREAD

**Issue by jcsomac** [caffeinalab/ti.goosh#25]
Well.. this is happening when i try to build the app in the device.
i just add the module in the titanium project with other code, just adding, compiling and bum!

    [ERROR] :  Failed to run dexer:
    [ERROR] :  
    [ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added:     Lcom/google/android/gms/common/AccountPicker;
    [ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added:     Lcom/google/android/gms/common/ConnectionResult;
    [ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added:     Lcom/google/android/gms/common/ErrorDialogFragment;
    [ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GoogleApiAvailability;
    [ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesNotAvailableException;
    [ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesRepairableException;
    [ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesUtil;
    [ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GooglePlayServicesUtil$zza;
    [ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/Scopes;
    [ERROR] :  
    [ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
    [ERROR] :  java.lang.RuntimeException: Translation has been interrupted
    [ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
    [ERROR] :  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
    [ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:277)
    [ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:245)
    [ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
    [ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
    [ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
    [ERROR] :  	... 4 more

if i remove the module, the app is created with no problem.
I am using classic development with SDK 5.5.1 GA, TiGoosh 1.6.2
Thanks in advance.

**Comment by progress44** [comment]
Hi, 

this is not a module issue. It's a problem with multidexing. 
check this closed issue https://github.com/caffeinalab/ti.goosh/issues/15 on how to resolve it
