### ISSUE TITLE
Titanium SDK 6.0.0 support?

### ISSUE THREAD

**Issue by tav3lla** [caffeinalab/ti.goosh#26]
Thanks!

**Comment by progress44** [comment]
It should be supported. We have yet to test it though. If you have the opportunity to test it let us know if it works
Thanks

**Comment by tav3lla** [comment]
I have already tested but it's not supported.

**Comment by progress44** [comment]
Alright, we'll have a look at it as soon as possible. Thanks

**Comment by progress44** [comment]
Hi @tav3lla. We have just released version 1.7.1 of ti.goosh built for SDK 6.0.0
Thanks

**Comment by tav3lla** [comment]
Thank you!

**Comment by netoramalho** [comment]
I had trouble using the last build because the apiversion was in 2. 
`has apiversion=2, but the selected SDK supports module apiversion=3 on platform=android`

**Comment by progress44** [comment]
@netoramalho you're right, updated it now.
