### ISSUE TITLE
inBackground is true while it should be false

### ISSUE THREAD

**Issue by GerbenHofman** [caffeinalab/ti.goosh#27]
Hello,

I've successfully implemented this module to my app and I stumbled upon something. I've made a request, while the app is in foreground, to Google to send me a notification. This works and the app correctly tells me that inBackground is false. Now that I've added the `force_show_in_foreground: true` node to the same request it tells me that inBackground is true whilst it's not.

- Ti SDK 5.4.0
- Android 6.0.0
- HTC one M8

EDIT: I forgot to mention that this issue only appears when you click on the notification.

**Comment by progress44** [comment]
I'll have a look at this issue later this afternoon. Thanks for notifying us :)

**Comment by progress44** [comment]
I verified the code and the value of `inBackground` is the exact value of `!TiApplication.isCurrentActivityInForeground()`. It isn't mutated by any action, not even by `force_show_in_foreground`. The logic behind these two variables is that if the app is in the background the notifications are shown normally. If the app is in the foreground, the notifications aren't shown unless you force them using `force_show_in_foreground: true`.

**Comment by progress44** [comment]
Can't replicate. Reopen the issue if it hasn't been resolved
