### ISSUE TITLE
Fatal exception when I push notification from Advance REST Client

### ISSUE THREAD

**Issue by junweimah** [caffeinalab/ti.goosh#28]
This is how I pushed it from REST Client

to : https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization:key=my_key
payload : { "data": {
    "alert": "Testing",
    "title": "This is title test",
  	"tag":"this is tag",
  },
  "to" : my_device_token
}

I received the notification on my phone, but my application crashed. This is the log 

![image](https://cloud.githubusercontent.com/assets/21700014/20549663/71977efc-b169-11e6-8d99-07d4f4ef4278.png)

What is the problem? Thanks

**Comment by junweimah** [comment]
I have solved the following error by changing the payload and URL to the following : 

URL : https://android.googleapis.com/gcm/send
payload : 
      "data":{
  	"data":{
      "alert": "Testing",
      "title": "This is title test",
      "tag":"BB",
      "id":2,
      }
 	 },
       "to" : my_device_token

But now however, another problem arise

When I push when my app is opened, I get this empty notification : 

![screenshot_20161123-122011](https://cloud.githubusercontent.com/assets/21700014/20551135/8dbf6294-b177-11e6-9d37-853dbc071dc8.png)

When I push when my app is closed, I get 2 notifications. 1 is showing the correct text, one is empty, just like the one i got when my app is open

![screenshot_20161123-121944](https://cloud.githubusercontent.com/assets/21700014/20551149/b9f89380-b177-11e6-9175-6eefea930284.png)

In both cases, when my app is closed and is opened, in the log file i am getting the correct data in the callback :

![image](https://cloud.githubusercontent.com/assets/21700014/20551164/e1d8c708-b177-11e6-9463-a52259a784c4.png)

Why is the notification come in differently when the app is opened and closed?

**Comment by progress44** [comment]
hi @junweimah. Please check the documentation when sending the payload. It seems like a malformed payload. I tried sending notifications both with the app closed and with it opened before the release and they worked. I'll make some other tests just in case

**Comment by junweimah** [comment]
@progress44 Ok I'll do some changes accordingly. thanks.

**Comment by progress44** [comment]
@junweimah anytime. Let me know if it's fixed

**Comment by junweimah** [comment]
I have checked everything and honestly I am not sure whether it's the payload problem.

I pushed using this payload, which is almost the same as the previously try in my second comment  in this post: 

```
{
 "data": {
  	"data":{
             "alert": "Testing alert and content",
             "title": "this is title",
             "tag": "bb",
             "vibrate": true,
             "sound": true,
             "id": 2,
    }
 },
   "to" :my_device_token
}
```

But now I am getting no notification, but a blank alert in the middle of the screen when the app is opened : 

![img_20161124_111229](https://cloud.githubusercontent.com/assets/21700014/20585625/8fb34d70-b237-11e6-948b-2d564429362f.jpg)

For when app is closed, the same still happens, I am getting 2 notifications, one is showing the correct text, one is empty

**Comment by junweimah** [comment]
Latest update

Everything is fixed. There are some problems in my other module and I fixed them.

Thanks.

**Comment by Bertuzb** [comment]
also had this problem here. Sending the payload with data.data.alert as shown above worked for me as well. This syntax seems really odd...

Can you release this soon?

**Comment by progress44** [comment]
We kept this syntax to maintain the same data structure with iOS so it will most probably remain the same.

**Comment by Bertuzb** [comment]
Im sending data on php-side using:
```
$data = json_encode(
    [
      'to' => $params[ 'registrationid' ],
      'notification' => [
        'title' => 'Welcome to my app',
        'body' => 'The Message',
        'icon' => 'uzb_a',
        'color' => '#c12139',
      ],
      'data' => [
        'data' => [
          'alert' => 'SOMEDATA'
        ]
      ]
    ]
  );
```

This is the exact data retrieved under TiGoosh.registerForPushNotifications-callback function (Android):
![schermafbeelding 2017-02-02 om 16 41 30](https://cloud.githubusercontent.com/assets/10498595/22556152/7b83feec-e966-11e6-93f2-2dc86bf760f5.png)

This is the exact data retrieved using Ti.Network.registerForPushNotifications-callback function (iOS):
![schermafbeelding 2017-02-02 om 16 37 42](https://cloud.githubusercontent.com/assets/10498595/22556005/014a23d6-e966-11e6-8c6b-180919fd7b62.png)

__________________________________________________________________

Something seems off here

**Comment by progress44** [comment]
Yeah definitely
