### ISSUE TITLE
Receiving notification while in background calls callback immediately

### ISSUE THREAD

**Issue by DFoxinator** [caffeinalab/ti.goosh#3]
First off, outstanding job on this module. It seems to work really well for the most part, and I'm really excited to replace the old push notif module in my app with this.

I'm having one issue, as described in the title. In the documentation, the expected behavior for when the app is in the background is, "if the app is in background, the standard OS view for incoming notifications is shown. If you click on that banner, the callback is invoked with the notification payload + the property inBackground = true" That's exactly the behavior I would like, but it doesn't seem to be working.

If my app is in the background and a notification is received, callback is called right away rather than when the notification is tapped. However, if you completely close the app, then it works as expected (callback gets called with expected data right when the app starts).

Any help is greatly appreciated, thanks!

**Comment by mreed49** [comment]
Agreed, great job on this module!

I've having a different (but related) experience. When the application is in the background (not terminated), the callback is never called - even after tapping the notification. If the application is closed (AKA terminated), tapping a notification starts the application and calls the callback as expected. Is there something that I could be doing wrong? I could provide some code samples if that would be helpful. Any insight greatly appreciated, thank you!

I tested this on Android 4.2.2 and Android 6.0.1.

**Comment by kopiro** [comment]
Hi @DFoxinator and @mreed49, we experienced the same issue.
We understood where is the problem but we need to refactor the Intent service module totally.
Probably we'll solve in next week.

**Comment by kopiro** [comment]
Thanks to @progress44 for helping me to find the right solution.

**Comment by DFoxinator** [comment]
Awesome @kopiro and @progress44! Thank you for the update and thanks for fixing!

**Comment by mreed49** [comment]
Thank you @kopiro and @progress44 , it works great!
