### ISSUE TITLE
Valid Titanium Module

### ISSUE THREAD

**Issue by macazaga** [caffeinalab/ti.goosh#31]
I´m not using additional modules and i get this error:

`Could not find a valid Titanium module id=ti.goosh version=latest platform=android deploy-type=development.`

```
[ERROR] :  Could not find all required Titanium Modules:
[ERROR] :     id: ti.goosh	 version: latest	 platform: android	 deploy-type: development
```

```
   <modules>
    <module platform="android">ti.goosh</module>
  </modules>
```

I installed the module using gittio and is located under modules/android/ti.goosh

Any ideas?

Thank you!

**Comment by progress44** [comment]
Youre probably using the latest ti.goosh version but not titanium sdk 6.0. Version 1.7.2 is compiled for sdk 6.0 and doesn't work on old sdks

**Comment by macazaga** [comment]
That was the problem, thanks a lot!
