### ISSUE TITLE
For Android, anyway to expand the notification to see all the text if my message is too long?

### ISSUE THREAD

**Issue by junweimah** [caffeinalab/ti.goosh#32]
Title.

I plan to have a longer alert message and they cannot fully be shown

**Comment by netoramalho** [comment]
You can send a larger message using the **big_text** parameter, and in the alert send it in a summarized way.

**Comment by junweimah** [comment]
For testing this is my payload : 

```
             "alert": "alert",
             "title": "this is title",
             "icon" : "http://i.imgur.com/IGxUq3Z.jpg",
             "vibrate": true,
             "sound": true,
             "big_text" : "this is big text"
             "force_show_in_foreground" : true,
             "id": 2,
```

However I cant see the message "this is big text" from my notification. I am only seeing "alert" and "this is title", and the notification is not expandable

**Comment by netoramalho** [comment]
I tested it here and it worked normally, it follows the information from my test, I hope something helps you figure out what might be happening.

**Payload**
```
{
    "data": {
        "id": "2",
        "vibrate": true,
        "title": "Netto Ramalho",
        "icon": "https://s-media-cache-ak0.pinimg.com/avatars/neto_ramalho_1_1403441759_140.jpg",
        "alert": "3 new messages",
        "big_text": "- Message 1\n- Message 2\n- Message 3"
    }
}
```

**Prints**
https://drive.google.com/open?id=0BylxnWR5r-V3RjFKdzFnSEd2R0E

**Environment**
sdk-version: 5.5.1.GA
module-version: 1.6.2
android-version: 6.0

**Comment by junweimah** [comment]
hmm. I am using exactly the same environment as yours, only that I am using a rooted device, not sure if that is the problem.

Ill try to figure it out. thanks for the help

**Comment by junweimah** [comment]
OK. I copied and tested your payload. It is working. 
Ill make some changes accordingly

Thanks again

**Comment by junweimah** [comment]
Hi I have another question

In your screenshot, there is a small icon at the bottom right of your notification icon, what is that? I am having a similar thing, but an empty circle for me. Any way to remove it?

**Comment by netoramalho** [comment]
See section **Set the icon for the tray** in the **readme** file, explain how to change this icon, I do not know how to remove, but anyway I think it is not a good idea, this icon is displayed in other places where it is important the user to identify the symbol of its application

**Comment by kopiro** [comment]
You can't remove that icon.
If you don't set the icon, no notification has been displayed; we put an empty circle as a default for this reason.
