### ISSUE TITLE
How to subscribe for topic?

### ISSUE THREAD

**Issue by ananth-kumar** [caffeinalab/ti.goosh#34]
How do i subscribe for a topic !

Thanks,

**Comment by kopiro** [comment]
`TiGoosh.subscribe(TOPIC)`

**Comment by ananth-kumar** [comment]
No :(
it says "TiGoosh.subscribe method not found"

**Comment by kopiro** [comment]
Sorry, I mixed up the question.
What is a topic, in your question? Are you using AWS?

**Comment by ananth-kumar** [comment]
GCM/FCM has option to subscribe to a topic..
Please check this..
https://developers.google.com/cloud-messaging/topic-messaging

**Comment by progress44** [comment]
We haven't implemented this so far.

**Comment by m1ga** [comment]
https://github.com/caffeinalab/ti.goosh/pull/82

**Comment by Jei** [comment]
Closing this, as it's been added in the 3.0.0 release.
