### ISSUE TITLE
Integration with Pushbots

### ISSUE THREAD

**Issue by almsx** [caffeinalab/ti.goosh#4]
Hello,

I am currently using as Push Notifications service to service Pushbots, where unfortunately there is no support for Appcelerator.

Create a function that makes the record via its API on my device when using TiGoosh for Token generation.

However, the listener at least TIGoosh using this service (Pushbots) does not work.

I'm combining bad services? Or something is wrong? Any support will be very useful.

Greetings from Mexico

**Comment by kopiro** [comment]
Hi, maybe the payload the Pushbots sends it not TiGoosh compatible.
You can try to inspect this payload (if you haven't it) by typing:

`adb logcat | grep TiGoosh`

and post the results here.

**Comment by kopiro** [comment]
Hi @almsx, any update?
