### ISSUE TITLE
GET_ACCOUNTS permission requires privacy policy

### ISSUE THREAD

**Issue by davide-ensini** [caffeinalab/ti.goosh#40]
Play Store wants me to provide a privacy policy for my apps, because this module is requesting "android.permission.GET_ACCOUNTS".

Is that permission required, or could it be removed?

This is the exact message I get: "Your app has an apk with version code 21 that requests the following permission(s): android.permission.GET_ACCOUNTS. Apps using these permissions in an APK are required to have a privacy policy set". I also got an email telling me to comply within March, 15,  or else.

**Comment by Jei** [comment]
Reading from http://stackoverflow.com/questions/18444227/get-accounts-permission-while-using-gcm-why-is-this-needed , it seems that GET_ACCOUNTS is no longer required by the GCM library. We'll try out the module without it and see if we can remove this permission in the next release.

**Comment by progress44** [comment]
Fixed with commit https://github.com/caffeinalab/ti.goosh/commit/5c258a4d748ddddcc6d8e6d60038d9d23dfdb309
