### ISSUE TITLE
Any way to not show the alert while in app for ios, force_show_in_foreground is set to false

### ISSUE THREAD

**Issue by junweimah** [caffeinalab/ti.goosh#41]
I want to not show in app while the app, already set force_show_in_foreground to false, but still happens

![image](https://cloud.githubusercontent.com/assets/21700014/22876912/d5518cf0-f20d-11e6-81a8-20c7b73429b7.png)

While in app I only wanted to show something like this, taken from whatsapp

![export 1](https://cloud.githubusercontent.com/assets/21700014/22877016/60d437e6-f20e-11e6-860b-8a649762638c.png)

**Comment by progress44** [comment]
Ti.goosh only works for Android. I think you added the alert in your app somewhere. Search for `alert()`
