### ISSUE TITLE
Push Notification not receiving in background but working in foreground

### ISSUE THREAD

**Issue by Robbe92** [caffeinalab/ti.goosh#45]
Hi,
The FCM works fine when the app is in foreground and a push comes, but when the app is in background and the system tray notification is clicked , it just opens up the app without passing any intent extras.

**Comment by progress44** [comment]
There are two types of messages data messages and notification messages. Data messages are handled here in `onMessageReceived` whether the app is in the foreground or background. Data messages are the type traditionally used with GCM. 
Notification messages are only received here in `onMessageReceived` when the app is in the foreground. When the app is in the background an automatically generated notification is displayed. 

When the user taps on the notification they are returned to the app. **Messages containing both notification and data payloads are treated as notification messages**. The Firebase console always sends notification messages. 

`onMessageReceived` is the function in the module handling the incoming notifications

For more see: https://firebase.google.com/docs/cloud-messaging/concept-options
