### ISSUE TITLE
Set senderid at runtime

### ISSUE THREAD

**Issue by Bertuzb** [caffeinalab/ti.goosh#48]
Any way to define the following line at runtime:
```
<property name="gcm.senderid">1118111711111</property>
```

The issue im having is that I want a separate environment for development devices vs production devices. Firebase doesnt seem to particularly support this, so the only way is to define 2 projects.

However, when registering APN tokens with FCM/GCM (see https://developers.google.com/instance-id/reference/server#create_registration_tokens_for_apns_tokens), i am able to pass `sandbox:true/false` which determines which Certificate (Apple developers config) GCM should use when sending to that Apple device.

So in my Firebase project I can seem to define a dev+prod environment for iOS, but for Android there is none.

**Comment by progress44** [comment]
Try setting it using `Ti.App.Properties.setString('gcm.senderid', '1118111...');` make sure to remove it from tiapp.xml if you go this way as it makes the property readonly.

**Comment by Bertuzb** [comment]
yes awesome that seems to work. I'm tempting to close but what about something like 

```javascript
require('ti.goosh')(1118111...);
```

or
```javascript
var tg = require('ti.goosh');
tg.setSenderId(1118111...); // since there is also getSenderId() if i look at the source?
```

**Comment by progress44** [comment]
That wouldn't work. For now the above is the only solution if it works. The `getSenderId()` method gets it from the `Titanium.App.Properties` directly

**Comment by Bertuzb** [comment]
in the current implementation it wouldnt no. But there is something to say for the discrepancies of `app/config.json` vs `tiapp.xml`. By defining it in the javascript you give the power to the user since they can define how they retrieve configuration.

It seems very reasonable to have it as a constructor argument, vs defining a hard property somewhere.

**Comment by progress44** [comment]
The main focus of this module is to maintain full compatibility with how iOS notifications are handled by Titanium. Creating a specific method is a possibility. Something like `TiGoosh.setSenderId()` but it doesn't seem critical at the moment.

**Comment by Bertuzb** [comment]
The main focus of this module is to get Android notifications working at all. There is no compatibility/parity with iOS vs the Android implementation. The only thing that corresponds is the function name itself `registerForPushNotifications` and `success`/`error`/`callback` as arguments (and its invocations).

A programmer needs to attach custom handlers for iOS anyway so I bet most programmers end up with a separated setup for 50% of the code.

**Comment by progress44** [comment]
That shouldn't be the case. The same callback functions should work on both Android and iOS. We wanted to make sure of this and it's the same reason why we expect the payload to be formatted in a certain way.

**Comment by progress44** [comment]
We usually do something like this 
```javascript

function requireOrNull(moduleId) {
	var module = null;
	
	try {
	   module = require(moduleId);
	} catch(e) {
	  Ti.API.error("Module couldn't be loaded")
	}
	
	return module;
}

var Push = OS_ANDROID ? requireOrNull('ti.goosh') : Ti.Network;

Push.registerForPushNotifications(callback, success, error);
```

And then we use `Push` everywhere. 
Check out [Trimethyl](https://github.com/trimethyl/trimethyl/) and in particular [Notifications](https://github.com/trimethyl/trimethyl/blob/master/framework/notifications.js#L35)
