### ISSUE TITLE
data.alert required

### ISSUE THREAD

**Issue by Bertuzb** [caffeinalab/ti.goosh#49]
Can you elaborate the following implementation:

https://github.com/caffeinalab/ti.goosh/blob/5e490fcae8dd9ccbd1e4900d70757edfa0b46e72/android/src/ti/goosh/IntentService.java#L117

Is the `alert` property meant to be the `body` property as seen here: 

https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

I'm confused why it is required. Can you put something in the docs for this or clarify here?

**Comment by progress44** [comment]
@Bertuzb Yes the alert property is meant to be the body of the notification. The module requires `alert` to keep compatibility with iOS
