### ISSUE TITLE
Android issue when close app

### ISSUE THREAD

**Issue by quocbao1087** [caffeinalab/ti.goosh#51]
Hi, I have an issue.
When I press Home button to view phone's home screen. Click on notification > app open detail page.
But when I close app > click notification > only open app, not open detail page.
Can you please help on this?

**Comment by hannta** [comment]
I have similar issue.

When the app is in foreground, I receive the notification, `callback` is executed correctly with the data.

If the app is closed or in background, I click the notification, `callback` not get called.

Using TiSDK 6.0.4.GA & ti.goosh 2.0.6, FCM (node-pushnotifications / node-gcm) for sending notifications.

**Comment by progress44** [comment]
As discussed in previous issues, if you are using FCM, make sure to not use `notification`. 

The notification object behaves like (quote): "FCM automatically displays the message to end-user devices on behalf of the client app. Notification messages have a predefined set of user-visible keys and an optional data payload of custom key-value pairs."

Use only `data`. Check out the documentation on how to send the payload correctly.

**Comment by quocbao1087** [comment]
HI, I am using GCM and push notification data same as document page: https://github.com/caffeinalab/ti.goosh

**Comment by progress44** [comment]
@quocbao1087 which version of ti.goosh are you using and what device are you testing it on?

**Comment by quocbao1087** [comment]
I am using TiSDK 6.0.4.GA & ti.goosh 2.0.6

**Comment by progress44** [comment]
Some devices require particular permissions from the user. What device are you using?

**Comment by hannta** [comment]
@progress44 im setting the data as `data` object. Im able to get `data` correctly when the app is in foreground, so I quess the issue is not in data it self?

My device Nexus 5.

**Comment by progress44** [comment]
@hannta whether `data` is correct or not is irrelevant if you include `notification` because FCM will only consider `notification`

**Comment by quocbao1087** [comment]
I am using TiSDK 6.0.4.GA & ti.goosh 2.0.6 
I am testing on Samsung Galaxy A5 2016. Android 6.0.1

> When the app is in foreground, I receive the notification, callback is executed correctly with the data.
> If the app is closed, I click the notification, callback not get called.

**Comment by progress44** [comment]
I'll check this out but it has been tested before.

**Comment by hannta** [comment]
Thanks @progress44, my issue was because incorrect data (im using FCM).

**Comment by mitulbhalia** [comment]
Hi @hannta 
Can you please provide your solution for this issue?

My issue is that callback is not called when app is completely closed. In all other aspects, it works well.
