### ISSUE TITLE
Unable to set custom notificationicon.png 

### ISSUE THREAD

**Issue by hannta** [caffeinalab/ti.goosh#52]
I try to set custom `notificationicon.png`, as described on readme. My icon file is in `app\platform\android\res\drawable-*\notificationicon.png` folders (mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi).

When my app receives notifications, devices displays app icon as notification icon (which is default/fallback icon). 

I have also tried to use the icon provided by ti.goosh (removed my own icon, so the icons comes from module), but with same result.

When I build my app, titanium packs `notificationicon.png` to `drawable-*-v4` folder, which should not be the issue?

Im using TiSDK 6.0.4.GA

**Comment by hannta** [comment]
I was sending incorrect data through FCM. Fixed data and not the icon is also working correctly.

**Comment by Abdelalim-dev** [comment]
@hannta can you please specify what you fixed in the data, i'm kinda having the same issue, thanks
