### ISSUE TITLE
Uncaught Failed resolution of: Lcom/google/android/gms/R$string;

### ISSUE THREAD

**Issue by mark22** [caffeinalab/ti.goosh#53]
Finally got the module to run after a few hoops then when I tried to registerforpushnotifications I now get this error.  Any ideas?

Ti.Goosh 2.0.6
Titanium 6.0.4

[ERROR] :  TiExceptionHandler: (main) [204,206] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [0,206] - In /app.js:341,11
[ERROR] :  TiExceptionHandler: (main) [0,206] - Message: Uncaught Failed resolution of: Lcom/google/android/gms/R$string;
[ERROR] :  TiExceptionHandler: (main) [0,206] - Source: 		TiGoosh.registerForPushNotifications({
[ERROR] :  V8Exception: Exception occurred at /app.js:341: Uncaught Failed resolution of: Lcom/google/android/gms/R$string;
[ERROR] :  V8Exception: Failed resolution of: Lcom/google/android/gms/R$string;

Not sure if its relevant or related but incase it is, I also use Ti.GA and used the gps-jars folder fix which works and allows me to atleast launch the app with both modules enabled.  But as soon as I try to registerforpush then this error pops up

**Comment by progress44** [comment]
Make sure the app is using the correct module version. Copy both Ti.GA and ti.goosh in your app's *modules* folder. In tiapp.xml specify the version along the module name for ti.goosh and ti.ga.
Let me know if this fixes the issue

**Comment by mark22** [comment]
@progress44 I believe it is using the correct module version as the app successfully launches (it would not even launch without the gps-jars fix).

Ti.Goosh 2.0.6
Ti.GA 3.0.7

I only have 1 version of each of the modules in fact.

However, this bug or exception pops up if I try to actually call the **registerforpushnotifications** function.

Thanks much!  Can't wait to get Ti.Goosh running

**Comment by mark22** [comment]
Even if I delete Ti.GA altogether and run Ti.Goosh alone I have the same set of errors

**Comment by antonioduran** [comment]
Hello. Good evening. I have the same issue also.

Does anyone know if there is a workaround for this? I have the same issue:
```
[ERROR] TiExceptionHandler: (main) [1297,1297] ----- Titanium Javascript Runtime Error -----
[ERROR] TiExceptionHandler: (main) [0,1297] - In /tailored.js:1557,51
[ERROR] TiExceptionHandler: (main) [0,1297] - Message: Uncaught Failed resolution of: Lcom/google/android/gms/R$string;
```

Thanks, and best,
Antonio

**Comment by progress44** [comment]
Hi all,

I'm testing the module on a clean app adding the following modules as well.

- ti.ga (3.0.0)
- ti.map (3.0.1)

The steps I took are these:

1. Created new app
2. Added the modules ti.ga, ti.goosh, ti.map locally to the app
3. Added jar `google-play-services-gcm+analytics+maps.jar` in **lib** folder in ti.goosh
4. Removed all jars from ti.ga lib folder and ti.map lib folder
5. Removed assets/Readme from **ti.goosh.jar** (it's a simple zip archive)
6. ran app

App opens. At this point I changed **alloy.js** to execute registerForPushNotifications() as in the documentation

Added `gcm sender id`

```
  <property name="gcm.senderid">785852287040</property>
```

When launching the app, in the terminal I see correctly 

```
Notifications: device token is fno50kOLlOU:APA91bFTezbb-nqsx5LeO0mPot117GEJc3amuyPGxludPqrRBJv7QBZiMPSnMDsOyVt3jJY8GqIQn6-feqnP_B3s8rj4kYaT20gQpygVtPMi_0D1nt_lUdHj6NP3slHyx4uCfa8CDf8k
```

**Comment by alangumer** [comment]
Make sure to have Google Play Services APK (https://developers.google.com/android/guides/setup)

For Genymotion:
Visit opengapps.org
Select x86 as platform
Choose the Android version corresponding to your virtual device
Select nano as variant
Download the zip file
Drag & Drop the zip installer in new Genymotion virtual device (2.7.2 and above only)
Follow the pop-up instructions
