### ISSUE TITLE
"No notification in Intent" when app is completely closed

### ISSUE THREAD

**Issue by bert-w** [caffeinalab/ti.goosh#57]
See image:
<img width="898" alt="schermafbeelding 2017-05-23 om 17 19 44" src="https://cloud.githubusercontent.com/assets/10498595/26361702/127d4de6-3fdc-11e7-86fa-483cf3166807.png">

I'm using the exact syntax from the PHP sample in the readme, for test purposes. The callback is not triggered within the Titanium JS.

The above issue only happens when the app is completely closed. Having it in background results in correct behaviour.

**Comment by danimarin** [comment]
Hi, I had the same issue and I fixed it changing the **parseBootIntent** function from **TiGooshModule.java**.

It seems that it was not getting the "data" extra as a string successfully.

`	public void parseBootIntent() {
		try {
			Intent intent = TiApplication.getAppRootOrCurrentActivity().getIntent();
			String notification = "";

			Bundle extras = intent.getExtras();
			if (extras != null) {
				notification = extras.getString("data");
				Log.d(LCAT, "Extra data: " + notification);
			}
			
			if (intent.getExtras() != null) {
				
				for (String key : intent.getExtras().keySet()) {
	                Object value = intent.getExtras().get(key);
	                Log.d(LCAT, "Key: " + key + " Value: " + value);
	            }
			}

			if (!notification.isEmpty()) {
				sendMessage(notification, true);
			} else {
				Log.d(LCAT, "No notification in Intent");
			}
		} catch (Exception ex) {
			Log.e(LCAT, ex.getMessage());
		}
	}`

**Comment by mitulbhalia** [comment]
Hi @bert-w 
Can you please tell me that is it resolved in v2.0.7 or if not then can you please share your compiled module with the above change?

**Comment by Lenndev** [comment]
@bert-w in what version of ti-goosh and ti sdk did you encounter this problem in?

**Comment by AppWerft** [comment]
I changed to 
```
if (extras != null) {
	notification = extras.getString(TiGooshModule.INTENT_EXTRA);
}
```
Hint: "data" != TiGooshModule.INTENT_EXTRA

And I have changed in IntentService:
```
NotificationManager notificationManager = (NotificationManager) TiApplication
				.getInstance().getSystemService(Context.NOTIFICATION_SERVICE);
		launcherIntent.putExtra(TiGooshModule.INTENT_EXTRA, message.toString());
```

**Comment by Lenndev** [comment]
is this still a bug or is it fixed with your ( @AppWerft ) change?

**Comment by kopiro** [comment]
Hey guys, issue solved :)
https://github.com/caffeinalab/ti.goosh/commit/22924ee861ae3e05f6fb2b2710db34521f0a8d4e
