### ISSUE TITLE
how can enable and edit the sound ?

### ISSUE THREAD

**Issue by furthurr** [caffeinalab/ti.goosh#58]
hi, I have a simple question 
how can enable and edit the sound of the notification push ?

**Comment by kopiro** [comment]
It's missing from the doc, sorry.

Anyway, you can set a sound by sending the `sound` property in the notification payload.

If true or default the default sound is used, otherwise you can specificy an audio file path located in the app bundle (/assets/).

**Comment by furthurr** [comment]
Thank you very much
