### ISSUE TITLE
Is android.permission.USE_CREDENTIALS necessary?

### ISSUE THREAD

**Issue by davidbnk** [caffeinalab/ti.goosh#61]
I switched to ti.goosh from other push module and received the following message when publishing my app:

> WARNING
> Users that have the APK with version code 215 may need to accept the android.permission.USE_CREDENTIALS permission, which may result in them not upgrading to this version of the app.

Can I safely remove this permission?

**Comment by progress44** [comment]
Hi! Are you using the latest version of ti.goosh? If I remember correctly we have removed the permission because **it is not needed anymore**. 
If we haven't removed it, try removing it yourself and let us know of the outcome.

**Comment by progress44** [comment]
I just checked previous issues and I had mistaken `GET_ACCOUNTS` permission with USE_CREDENTIALS which isn't removed. 
Commit-https://github.com/caffeinalab/ti.goosh/commit/5c258a4d748ddddcc6d8e6d60038d9d23dfdb309

Issue- #40 

Try removing it and keep us updated.
Thanks

**Comment by davidbnk** [comment]
I removed and everything worked fine in my SM-J500M Android 6.0

**Comment by progress44** [comment]
Thanks for the feedback @davidbnk

**Comment by kopiro** [comment]
:top:
