### ISSUE TITLE
GCM issue in updated appcelerator SDK (6.0.0 to 6.1.0 )

### ISSUE THREAD

**Issue by sauravsenapati1** [caffeinalab/ti.goosh#62]
Hello,

I am using your module ti.goosh for android push message which work fine up to Titanium SDK 5.5.1 but after update Titanium SDK (6.0.0 to 6.1.0 ), the module not working for Android. Please guide me to fix this issue?
Thanks in advance.

Following is the link for ti.goosh module.
http://gitt.io/component/ti.goosh

I found this types of error :-
[ERROR] : Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient$Info;
[ERROR] : Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient;

when i use this code in manifest with a meta-data tag

<android:name="com.google.android.gms.version" android:value="" />

I found this types of error :- 

[ERROR] :  Failed to package application: [ERROR] :   [ERROR] :  /Users/sumitchakrabarty/Documents/Appcelerator_Studio_Workspace/xxxxxxxx/build/android/res/drawable-xhdpi/account_tab_off_new_01977de8bc.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited [ERROR] :  /Users/sumitchakrabarty/Documents/Appcelerator_Studio_Workspace/xxxxxxxxx/build/android/res/drawable-xxhdpi/account_tab_off_new_01977de8bc.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

**Comment by progress44** [comment]
You don't need `<android:name="com.google.android.gms.version" android:value="" />`
Also check out the documentation for creating a `google-play-framework.jar` for your project.

**Comment by progress44** [comment]
https://github.com/caffeinalab/ti.goosh/tree/master/gps-jars
