### ISSUE TITLE
The Google Play services resources were not found

### ISSUE THREAD

**Issue by Wingee** [caffeinalab/ti.goosh#65]
I’m still getting the “The Google Play services resources were not found” error message.  
The only module in the app is ti.goosh and it's still failing. Any other ideas?

**Comment by progress44** [comment]
`The Google Play services resources were not found` this error doesn't stop neither the module nor the app from working. It's a bug in google play services. Check if there are other errors

**Comment by Wingee** [comment]
OK thank you. You're right it seems to be working correctly but showing the error message. Thanks
