### ISSUE TITLE
Error parsing data JSON

### ISSUE THREAD

**Issue by Wingee** [caffeinalab/ti.goosh#66]
I'm using FCM to send the push notification. With my app open I see this error:

E/ti.goosh.IntentService: Error parsing data JSON: Cannot cast com.google.gson.JsonArray to com.google.gson.JsonObject

Any ideas why I would be getting this?

**Comment by progress44** [comment]
What's the payload?

**Comment by Wingee** [comment]
Thanks, the payload had an error!
