### ISSUE TITLE
Background inBackground on Android HTCM8 and Samsing S7 Edge

### ISSUE THREAD

**Issue by Wingee** [caffeinalab/ti.goosh#67]
I'm having a problem with push notifications in the background. The push appears in the notification bar but only opens the app when clicked on and doesn't call the callback.

I've tried this on both an HTC M8 and Samsung S7 Edge - I saw there were previous threads where somebody was using a Huawei but that doesn't apply to me.

I'm using Titanium SDK 6.1.1GA and 2.0.6 of Ti Goosh
Any ideas gratefully received!!

Could it be manifest permissions?

**Comment by progress44** [comment]
I doubt it has to do with permissions. It would have raised an error. Does it show anything in the logs?

**Comment by Wingee** [comment]
It doesn't show anything in the logs at all! The app simply opens and that's it.

**Comment by Wingee** [comment]
Yep just tried this with my HTC M8 - put the app into the background. Then sent it a push notification. The push notifcation appears in the notification tray on the device (Although there is no icon, just a round circle) when I click on it, the app opens but there's nothing new in the log. 
Thanks in advance

**Comment by Wingee** [comment]
Any ideas why this might be happening or how I could resolve it please?
Thanks

**Comment by progress44** [comment]
I can't replicate the issue. Will continue to make tests when possible

**Comment by Wingee** [comment]
Thank you - it's obviously a payload format issue as I tried using your example code and it works successfully. Thanks for your help

**Comment by progress44** [comment]
Awesome! Glad it works
