### ISSUE TITLE
Notification not received on App

### ISSUE THREAD

**Issue by vertexinnovations** [caffeinalab/ti.goosh#68]
FCM is configured for the app and the module implemented. Notifications get to the app without issues if sent from FCM's console. However, when sent via PHP, the message is sent successfully, but never gets to the app.

Below is the result of the PHP function that sends the notification:

**{"multicast_id":5158963607793315745,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1499339081907693%1bada1511bada151"}]}**

**Comment by progress44** [comment]
1- check to have set the correct api keys in php
2- double check the payload

**Comment by vertexinnovations** [comment]
Thanks for your response.

I checked the api keys, and they are correct. Do you have a sample configuration in PHP, I can maybe compare to what I have?

**Comment by progress44** [comment]
There's this [file](https://github.com/caffeinalab/ti.goosh/blob/master/test-fcm) in the repo.

**Comment by Lenndev** [comment]
for some reason i can't send any push notifications via FCM console anymore... using the deviceToken i get from the deviceTokenSuccess callback (on registration) i get the error it is not registered... any ideas? never had this error before and haven't changed a thing...

**Comment by progress44** [comment]
@Lenndev Closing the issue, if you didn't find a solution, reopen it.
