### ISSUE TITLE
Implement additional keys and features

### ISSUE THREAD

**Issue by kopiro** [caffeinalab/ti.goosh#7]
In the payload, you can specify additionally:

| Key | Type | Description | Example |
| --- | --- | --- | --- |
| vibrate | Array | Set the vibration pattern to use. | `[100,200,0,100,200...]` |
| lights | String | Set the argb value that you would like the LED on the device to blnk, as well as the rate | `[ "#FF00FF", 200, 100 ]` |
| ongoing | Boolean | Set whether this is an ongoing notification. | `true` |
| group | String | Set this notification to be part of a group of notifications sharing the same key. | 'groupA' |
| when | Number | Set the time that the event occurred. Notifications in the panel are sorted by this time. | `1470058413` |
| only_alert_once | Boolean | Set this flag if you would only like the sound, vibrate and ticker to be played if the notification is not already showing. | `true` |

Docs: [https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html)

Be careful that:
* `vibrate` is already a param Boolean. We should check its implicit type.

**Comment by progress44** [comment]
Closed with the following commit https://github.com/caffeinalab/ti.goosh/commit/5246328cc56c3372ee0cae4ab6a0b821c0dc8a51
