### ISSUE TITLE
callback is not called when notification is clicked from notification tray

### ISSUE THREAD

**Issue by mitulbhalia** [caffeinalab/ti.goosh#70]
I am getting notification correctly but the callback method of module is not calling when notification is clicked.

Tested with module version 2.0.6, 2.0.7 and ti sdk 6.0.0.GA, 6.0.2.GA, 6.0.4.GA

**Comment by progress44** [comment]
Please do not open new issues for the same problem. 
#68 #57 #68

**Comment by mitulbhalia** [comment]
but my issue is little bit different. Callback is not called even the app is running in background.

**Comment by progress44** [comment]
How did you set up the module? Do you call the `registerforpushnotifications` on every app launch?

**Comment by mitulbhalia** [comment]
Yes and even app is not crashed when notification is clicked.

**Comment by mitulbhalia** [comment]
Do you know what should be the issue then?
Also app is hanged when push is received in foreground mode and push is not received when app is fully closed, not running in the background.

**Comment by progress44** [comment]
Check your payload, there's definitely something wrong there

**Comment by mitulbhalia** [comment]
From php side?

**Comment by progress44** [comment]
yeah

**Comment by mitulbhalia** [comment]
Ok, thanks

**Comment by mitulbhalia** [comment]
Here is my payload
$msg = array
          (
               "alert"     => $_POST['limitedtextarea'] . time(),
               "title"     => 'Notification',
               'sound'     => 'default',
               "vibrate"   => [100,50,50,50,100], 
               "badge"     => 1, 
               "tag"       => "Test" 
          );

**Comment by progress44** [comment]
It seems correct actually. I'll look into it as soon as I have some time

**Comment by mitulbhalia** [comment]
Thanks, did you have any chance yet?

**Comment by mitulbhalia** [comment]
Should i need to follow this link?
https://github.com/caffeinalab/ti.goosh/blob/master/test-fcm

**Comment by progress44** [comment]
Yeah it's helpful if you can try with that example. You just need to update your google API key and device token.

**Comment by mitulbhalia** [comment]
Its working...Thank you for your help.

Now the problem is i got below error first time when i clicked notification and thats why callback is not called but when i killed the app from background and run it again then it calls callback.
What should be the issue then?

No valid root or current activity found for application instance

**Comment by mitulbhalia** [comment]
No Worries.... I sorted out :)

**Comment by mitulbhalia** [comment]
@Lenndev 
I just followed the above link for back end side and it started to call callback function when app is in background but it still does not call callback when app is closed.
