### ISSUE TITLE
NPE on Notification

### ISSUE THREAD

**Issue by brandonfuller** [caffeinalab/ti.goosh#72]
TiGooshModule.java
Line 81:

`if (!notification.isEmpty()) {`

notification is initialized with an empty string but then gets a null data value on line 74.

Could you simply add a null check?

**Comment by davidbnk** [comment]
This bug is still happening on release 3.0.0

**Comment by progress44** [comment]
Should be fixed with this commit https://github.com/caffeinalab/ti.goosh/commit/74b28f911e18d239fad6eee790bd373cb1941db6
