### ISSUE TITLE
Not work sdk 6.1.1

### ISSUE THREAD

**Issue by necrocyber** [caffeinalab/ti.goosh#73]
Please, this module not work in sdk 6.1.1.

**Comment by necrocyber** [comment]
Sorry, work perfect in sdk 6.1.1  But this error show me: E/ti.goosh.TiGooshModule: sendMessage invoked but no messageCallback defined

**Comment by progress44** [comment]
Are you receiving notifications correctly even with the app closed?

**Comment by necrocyber** [comment]
Yes, the application receives notifications when it is closed, but the problem is the callback, which shows nothing when the background is true or false. Also pressing on the notification does nothing and shows these errors

**Comment by necrocyber** [comment]
[ERROR] :  E/ti.goosh.TiGooshModule: sendMessage invoked but no messageCallback defined
[WARN] :   W/ti.goosh.IntentService: Show Notification: FALSE

**Comment by necrocyber** [comment]
I have this two errors
E/ti.goosh.TiGooshModule: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.

**Comment by progress44** [comment]
Ignore this error as it seems to be a bug in google play services or android 
`[ERROR] : GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.`
Can you open the notifications with the app in background or opened?

**Comment by jcsomac** [comment]
I have the same error with SDK 6.1.2 using Ti.Goosh 2.0.7

`E/ti.goosh.TiGooshModule: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference`

i am driving me crazy.. can't find the way to receive push notifications..

**Comment by progress44** [comment]
@jcsomac what exactly doesn't work?

**Comment by kassemitani** [comment]
I have the same problem! with Titanium SDK 6.2.0  
`E/ti.goosh.TiGooshModule: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference`

**Comment by progress44** [comment]
Hi, check this [new release](https://github.com/caffeinalab/ti.goosh/releases/tag/v3.0.0). It should work with Titanium SDK 6.2.0

**Comment by kassemitani** [comment]
@progress44 Thank you its now working fine 👍

**Comment by ChanakyaSrinivas** [comment]
I have the same problem! with Titanium SDK 6.3.0

[ERROR] :  E/ti.goosh.TiGooshModule: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
[ERROR] :  E/ti.goosh.RegistrationIntentService: Failed to get GCM Registration Token:SERVICE_NOT_AVAILABLE
[ERROR] :  Notifications: Retrieve device token failed [object Object]

My envirionments:

Operating System	= Mac OS X 10.11.3
Node.js Version = 4.6.0
npm Version = 2.15.9
Titanium CLI Version = 5.0.14
Titanium SDK Version = 6.3.0.GA
ti.goosh version = 3.0.3
