### ISSUE TITLE
Android - silent notifications in background

### ISSUE THREAD

**Issue by AceMacLoud** [caffeinalab/ti.goosh#75]
Module is working at it should so far - many thanks for that :-)
Notifications arrive in the app via GCM or FCM when the app is running in the foreground and pop up as a notification when the app is in the background.
I'm having an issue regarding "silent" notifications (like "content-available in iOS) though:

As far as I understand the FCM and Module documentation, notifications shouldn't pop up in Notification Center when the "notification" part of the payload is empty. Additionally it says in the module documentation 

`If alert is not present, no message is shown in the notification center.`

I can't get this to work. No matter how I format the payload - without notification part, without alert & title, a message will always pop up in notification center. If I remove alert and title the message will contain a JSON string of the other fields in the message. I've been using the sample PHP code to send notifications:

    $json = [
      "registration_ids" => [
      "cqdjoSNQP44..."
      ],
      "data"    => [
        "data"  => [
          "alert"     => "Testing " . time(),
          "title"     => "The title",
          "vibrate"   => [100,50,50,50,100],
          "badge"     => 1,
          "tag"       => "APP",
        ]
      ]
    ];

Changing the payload to this will not pop up a notification but will still show it in the status bar as a white circle and will be visible when swiping down notification center:

    $json = [
      "registration_ids" => [
      "cqdjoSNQP44..."
      ],
      "data"    => [
        "data"  => [
          "myKey"       => "myVal",
        ]
      ]
    ];

Am I misunderstanding how this is supposed to work or is something not working as intended? What I'm trying to achieve is a silent notification that delivers data to the app, like content-available on iOS. The user shouldn't see this notification at all.

**Comment by lawjeremy** [comment]
I am having this same problem. If I set the alert field to an empty string the device shows an empty notification. If I set alert to null the app crashes in the background.

**Comment by DouglasHennrich** [comment]
I'm having the same problem:
![photo_2017-11-16_18-17-39](https://user-images.githubusercontent.com/10107024/32913763-7315139c-cafa-11e7-88ed-980efc112bbd.jpg)

**Comment by kopiro** [comment]
Something has changed on Android API.
We'll debug in this week. Thank you.

**Comment by DouglasHennrich** [comment]
Any news?

**Comment by DouglasHennrich** [comment]
What about who doesn't want to update to `Ti7` ?

**Comment by progress44** [comment]
[Here](https://github.com/caffeinalab/ti.goosh/releases/tag/v3.0.4) you go ;)

**Comment by DouglasHennrich** [comment]
Thank you so much!
