### ISSUE TITLE
priority Property support 

### ISSUE THREAD

**Issue by nuborian** [caffeinalab/ti.goosh#77]
Hi,

using the module is working, but on my device I only get the icon of the notification in my statusbar. There isn't any "banner" visible when the push is coming to the device. Is there any option to set, to change this?

**Comment by progress44** [comment]
Can you paste the payload you're sending to GCM? I'm not sure what might cause this

**Comment by nuborian** [comment]
Hey, thanks for your reply - I am using the parse-Server so it's their payload. Not sure what they are sending and what not.

**Comment by kopiro** [comment]
Hi @nuborian, try to send a custom JSON payload. IE:

```json
{ "alert": "Test", "title": "Title" }
```

**Comment by progress44** [comment]
Setting `force_show_in_foreground: true` will show the notification
