### ISSUE TITLE
[ERROR] Failed to run dexer:

### ISSUE THREAD

**Issue by usamecavga** [caffeinalab/ti.goosh#89]
Hi,

I have error when build.

`[ERROR] Failed to run dexer:
[ERROR]
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/GoogleSignInAccount;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/GoogleSignInOptions;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/GoogleSignInOptions$Builder;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/GoogleSignInOptionsExtension;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/internal/zzn;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/zza;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/auth/api/signin/zzb;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/ErrorDialogFragment;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/GoogleApiAvailability;
[ERROR]
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.RuntimeException: Translation has been interrupted
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
[ERROR]         at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
[ERROR]         at com.android.dx.command.dexer.Main.runDx(Main.java:289)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:247)
[ERROR]         at com.android.dx.command.Main.main(Main.java:94)
[ERROR] Caused by: java.lang.InterruptedException: Too many errors
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)
[ERROR]         ... 4 more`

ti.map version: 3.3.1
ti.goosh version: 3.0.3
ti sdk version: 6.3.0

**Comment by amigoni** [comment]
Getting the same error

**Comment by progress44** [comment]
Apparently you have two modules using the same google play services libraries. Try to use proguard to build a jar library with only the used classes from these libraries. 

Hopefully with Titanium 7.0.0 this won't be an issue anymore

**Comment by progress44** [comment]
Fixed with version 4 compatible with Titanium SDK 7.0.0
