### ISSUE TITLE
Unable to show our own icon in notification tray ?

### ISSUE THREAD

**Issue by ChanakyaSrinivas** [caffeinalab/ti.goosh#91]
Hi All, 

I fallows the documentation, 
When am sending notification from java server program am able to see the notification message in respective device but I was unable see the our own notification tray icon.

How to apply our own custom notification tray icon?

My envirionments:

Operating System		= Mac OS X 10.11.3
Node.js Version              = 4.6.0
npm Version                   = 2.15.9
Titanium CLI Version     = 5.0.14
Titanium SDK Version    = 6.3.0.GA

**Comment by ChanakyaSrinivas** [comment]
Hi all,

I replaced my own icon inside respective place with suggested resolution.
He am attached screen shot.
Please help me out, how can we get our own icon in notification tray.

![notification](https://user-images.githubusercontent.com/7510913/33658441-bd40058c-daa2-11e7-877e-b2ccee9407b4.png)

**Comment by Jei** [comment]
Reading from the [Android docs](https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html#overview11):
> Status bar icons are composed simply of white pixels on a transparent backdrop, with alpha blending used for smooth edges and internal texture where appropriate.

The notification icon has to be white.
If you want to change the _background color_ of the icon in the notification, you can use the parameter "color", as it's documented [in the readme](https://github.com/caffeinalab/ti.goosh#send-the-notification-from-your-server).
