### ISSUE TITLE
Requested module not found

### ISSUE THREAD

**Issue by stevencsw777** [caffeinalab/ti.goosh#94]
I have some problem trying to get the module working. I install the module Ti.goosh-2.0.0 on appcelerator, using sdk version 6.1.0. I call the module like this: 
var TiGoosh = require('ti.goosh-2.0.0'); 

and I got error Requested module not found: ti.goosh-2.0.0
I must had done something wrong but have no idea where.

Thanks

**Comment by progress44** [comment]
Hi 
The module name is 'ti.goosh' so the way to import it is `var TiGoosh = require('ti.goosh');` 
Check out the titanium documentation on how to use modules

**Comment by stevencsw777** [comment]
Thank you for the reply. I would really appreciate if you can give me some help. 
I did that as well but it still say requested module not found.

What I did is that I download the latest ti.goosh-3.0.0 and install it through the studio by going to Help > Install Module. Once it is installed, ti.goosh-3.0.0 appear on the root of the folder. 
Should I rename it to ti.goosh and put inside the modules folder?

**Comment by progress44** [comment]
You should put the module in the *modules* folder in the app's root folder like this `APP/modules/android/ti.goosh/3.0.0/` When you download the module, it already has the said structure `modules/android/ti.goosh/...`
